export const OPEN_SIDE_CONTACT = "OPEN_SIDE_CONTACT";
export const CLOSE_SIDE_CONTACT = "CLOSE_SIDE_CONTACT";
export const TOGGLE_SIDE_CONTACT = "TOGGLE_SIDE_CONTACT";
export const TOGGLE_SIDE_BAR = "TOGGLE_SIDE_BAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
